CONFIG_ZMK_POINTING=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_STUDIO_LOCKING=n

CONFIG_ZMK_BLE_MOUSE_REPORT_QUEUE_SIZE=1
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

CONFIG_ZMK_INPUT_PROCESSOR_REPORT_RATE_LIMIT=y
CONFIG_ZMK_INPUT_PROCESSOR_REPORT_RATE_LIMIT_DEFAULT=8

CONFIG_PROSPECTOR_ROTATE_DISPLAY_180=y
